# Generated by Django 3.1.2 on 2022-02-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20220121_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCenterDetails',
            fields=[
                ('Center_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pin_code', models.IntegerField()),
                ('VaccineCenterName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDetails',
            fields=[
                ('Vaccine_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_of_vaccine', models.CharField(max_length=255)),
                ('availability', models.BooleanField()),
                ('address', models.CharField(max_length=255)),
                ('Center_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.vaccinecenterdetails')),
            ],
        ),
    ]
