# Generated by Django 3.1.2 on 2022-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_vaccinecenterdetails_vaccinedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinedetails',
            name='availability',
            field=models.IntegerField(),
        ),
    ]
