# Generated by Django 3.1.2 on 2022-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20220201_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecenterdetails',
            name='Center_Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinedetails',
            name='Vaccine_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
