# Generated by Django 3.1.2 on 2022-02-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20220201_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinedetails',
            name='address',
        ),
    ]
