# Generated by Django 3.1.2 on 2022-02-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_vaccinedetails_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinedetails',
            old_name='Center_Id',
            new_name='Center',
        ),
    ]
