# Generated by Django 3.1.2 on 2022-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20220203_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('vaccine', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
