# Generated by Django 3.1.2 on 2022-02-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_bookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='username',
            field=models.CharField(default='username', max_length=255),
            preserve_default=False,
        ),
    ]
