# Generated by Django 3.1.2 on 2022-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_bookingdetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='aadhar',
            field=models.BigIntegerField(),
        ),
    ]
