# Generated by Django 3.1.2 on 2022-02-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20220205_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
